cc_library(
    name = "argh",
    srcs = ["argh.cc"],
    hdrs = ["argh.h"],
    deps = ["positional_arg"],
    visibility = ["//visibility:public"]
)

cc_library(
    name = "positional_arg",
    srcs = ["positional_arg.cc"],
    hdrs = ["positional_arg.h"]
)